package by.bsuir.app.util.connection;

public enum Commands {
    CLOSE_CONNECTION,
    ADD_OR_UPDATE_USER,
    DELETE,
    DELETE_BY_ID,
    AUTHORISATION,
    GET_ALL_USERS,
    GET_USER_BY_ID,
    GET_USER_BY_LOGIN,
    PASSWORD_RECOVERY,
    REGISTRATION,
    GET_USER_LOGS_BY_LOGIN,
    GET_ALL_USER_LAUNCHES,
    GET_LAUNCHES_COUNT_DATA,
    ADD_NEW_CAR,
}
