package by.bsuir.app.util;

public enum Commands {
    CLOSE_CONNECTION,
    USER_ADD_OR_UPDATE,
    DELETE,
    DELETE_BY_ID,
    AUTHORISATION,
    GET_ALL_USERS,
    GET_USER_BY_ID,
    GET_USER_BY_LOGIN,
    PASSWORD_RECOVERY,
    REGISTRATION,
    GET_USER_LOGS_BY_LOGIN,
    GET_ALL_USER_LAUNCHES,
    GET_LAUNCHES_COUNT_DATA,
    ADD_NEW_CAR,
    GET_ALL_MODELS,
    GET_ALL_CARS,
    SEND_MESSAGE_TO_USER,
    GET_ALL_FEEDBACKS_BY_USER_LOGIN,
    GET_ALL_USERS_FEEDBACKS,
    ADD_QUESTION_FROM_USER,
    ADD_ANSWER_ON_QUESTION,
    GET_ALL_MODELS_GROUPED_BY_QUANTITY,
    DELETE_CAR_BY_VIN,

}
